import Navbar from "./Navbar";
import Hero from "./Hero";
import About from "./About";
import Experiences from "./Experiences";
import Tech from './Tech';
import Work from "./Work";
import Feedbacks from "./Feedbacks";
import Contact from "./Contact"; 
import Map from "./Map";
import Chat from "./ChatBot";
export {Navbar, Hero,About, Experiences,Tech,Work,Feedbacks,Contact,Map,Chat}